Guard against incorrectly set $MWK.
mwk checks for bad MWK and errors out before calling make.

makefile checks for bad MWK in case it's called directly, without mwk.

newmeta checks for bad MWK and errors out before creating meta.json.

testMWK.sh tests the above.

README.rst describes the above.

diff --git a/mwk b/mwk
--- a/mwk
+++ b/mwk
@@ -1,3 +1,15 @@
 #! /usr/bin/env bash
 
-make -f $MWK/makefile $*
+# Run $MWK/makefile, passing any arguments through.
+# https://github.com/a3n/miki
+
+set -o errexit # Exit with error: any error.
+set -o nounset # Exit with error: an unset env variable is used.
+
+[ -d "$MWK" ] || (
+    echo "$0: Required: export MWK=~/top/directory/of/your/wiki"
+    echo "\$MWK = \"$MWK\""
+    exit 1
+)
+
+make -f "$MWK/makefile" $*
diff --git a/newmeta b/newmeta
--- a/newmeta
+++ b/newmeta
@@ -1,5 +1,19 @@
 #! /usr/bin/env bash
 
+# Create a usable starter meta.json,
+# with a link to the tracked file,
+# and a link to the resulting meta.json.
+# https://github.com/a3n/miki
+
+set -o errexit # Exit with error: any error.
+set -o nounset # Exit with error: an unset env variable is used.
+
+[ -d "$MWK" ] || (
+    echo "$0: Required: export MWK=~/top/directory/of/your/wiki"
+    echo "\$MWK = \"$MWK\""
+    exit 1
+)
+
 # Don't overwrite existing meta.json.
 [ -e meta.json ] && echo "ERROR: meta.json already exists." && exit 1
 
